defaults: &defaults
  working_directory: /tmp/boa-components
  docker:
    - image: circleci/node:10.0

install_js: &install_js
  run:
    name: Install js dependencies
    command: npm install

restore_npm_cache: &restore_npm_cache
  restore_cache: # special step to restore the dependency cache
    key: dependency-cache-{{ checksum "package.json" }}

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - *restore_npm_cache
      - run:
          name: Check versions and env
          command: |
            node --version
            npm --version
            docker --version
            docker-compose --version
            env
      - *install_js
      - run:
          name: Should not have any git not staged
          command: git diff --exit-code
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  lint:
    <<: *defaults
    steps:
      - checkout
      - *restore_npm_cache
      - *install_js
      - run:
          name: Export changed files
          command: |
            # changed files on this branch
            # `git diff --name-only master` but since the checkout used reset --hard
            # we need to parse the revs for the actual master
            echo 'export CHANGED_FILES=$(git diff --name-only $(git rev-parse origin/master)...)' >> $BASH_ENV
      - run:
          name: Check if npm run prettier was run
          command: |
            # if we use an empty string as a pattern grep will match everything
            if [ -z "$CHANGED_FILES" ]; then
              echo "no changes"
            else
              # Files that should have been formatted while working on this branch
              # CircleCI does not support interpolation when setting environment variables
              echo 'export FORMATTED_FILES=$(npm run --silent prettier:files | grep "$CHANGED_FILES")' >> $BASH_ENV
              source $BASH_ENV

              if [ -z "$FORMATTED_FILES" ]; then
                echo "no files for prettier were changed"
              else
                npm run prettier-ci $FORMATTED_FILES
              fi
            fi
      - run:
          name: Javascript Lint
          command: npm run lint
      - run:
          name: Typescript Lint
          command: npm run typescript
  test_unit:
    <<: *defaults
    steps:
      - checkout
      - *restore_npm_cache
      - *install_js
      - run:
          name: Unit tests
          command: npm run test-coverage
      - run:
          name: Check coverage generated
          command: |
            if ! [[ -s coverage/lcov.info ]]
            then
              exit 1
            fi
      - run:
          name: Coverage
          command: bash <(curl -s https://codecov.io/bash)
workflows:
  version: 2
  pipeline:
    jobs:
      - checkout
      - lint:
          requires:
            - checkout
      - test_unit:
          requires:
            - lint
