defaults: &defaults
  working_directory: /tmp/boa-components
  docker:
    - image: circleci/node:10.0

install_js: &install_js
  run:
    name: Install js dependencies
    command: npm install

restore_npm_cache: &restore_npm_cache
  restore_cache: # special step to restore the dependency cache
    key: dependency-cache-{{ checksum "package.json" }}

version: 2
jobs:
  checkout:
    <<: *defaults
    steps:
      - checkout
      - *restore_npm_cache
      - run:
          name: Check versions and env
          command: |
            node --version
            npm --version
            docker --version
            docker-compose --version
            env
      - *install_js
      - run:
          name: Should not have any git not staged
          command: git diff --exit-code
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test_unit:
    <<: *defaults
    steps:
      - checkout
      - *restore_npm_cache
      - *install_js
      - run:
          name: Export changed files
          command: |
            # changed files on this branch
            # `git diff --name-only master` but since the checkout used reset --hard
            # we need to parse the revs for the actual master
            echo 'export CHANGED_FILES=$(git diff --name-only $(git rev-parse origin/master)...)' >> $BASH_ENV
      - run:
          name: Unit tests
          command: npm run test-unit
workflows:
  version: 2
  pipeline:
    jobs:
      - checkout
      - test_unit:
          requires:
            - checkout
